### ISSUE TITLE
3.5.4.6.  Docker и Github [#504782]

### ISSUE THREAD

**Issue by velesov7493** [peterarsentev/job4j_features_bugs#1083]
С привязкой github-аккаунта к dockerhub-аккаунту ничего не выйдет - у community-аккаунта dockerhub уже нет такого функционала.

Поэтому предлагаю пойти другим путем: создавать и публиковать образ docker при сборке в Travis CI.

Для этого понадобится: 
+ в настройках репозитория на app.travis-ci.com определить значения 2-х защищенных переменных окружения: DOCKER_USERNAME и DOCKER_PASSWORD.
+ создать скрипт travis-deploy.sh, выполняющий сборку образа docker и его публикацию в dockerhub

```
#!/bin/sh
set -e
IMAGE="$DOCKER_USERNAME/job4j_shortcut"
mvn package -Dmaven.test.skip=true ;
docker build -t ${IMAGE} . ;
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin ;
docker push ${IMAGE} ;
exit 0 
```
+ внести соответствующие изменения в файл .travis.yml для исполнения тревисом вышеуказанного скрипта

```
language: java
dist: bionic

jdk:
  - openjdk14

services:
  docker

sudo: false

deploy:
  provider: script
  script: bash travis-deploy.sh
  on:
    branch: master

notifications:
  email:
    recipients:
      - <your-email>
    on_success: never # default: change
    on_failure: always # default: always
```
